esphome:
  name: auroralight
  platform: ESP32
  board: nodemcu-32s #esp32dev

wifi:
  use_address: auroralight.iot.cns.me
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  reboot_timeout: 1800s               
  
# captive_portal:

button:
  - platform: restart
    name: "Restart"

logger:
  level: DEBUG
  
api:
  password: !secret device_password
  # services:
  #   - service: set_pulse_total
  #     variables:
  #       new_pulse_total: int
  #     then:
  #       - pulse_counter.set_total_pulses:
  #           id: pulse_counter_id
  #           value: !lambda 'return new_pulse_total;'

# status_led:
#   pin: GPIO2
web_server:

ota:
  password: !secret device_password

esp32_ble_tracker:
  # scan_parameters:
  #   continuous: false
# bluetooth_proxy:

    # active: false

# binary_sensor:
#   - platform: ble_presence
#     mac_address: 00:24:e4:bf:ef:76
#     name: "CNS Watch"
# esp32_ble_tracker:

# external_components:
#   - source:
#       type: git
#       url: https://github.com/Ulrar/esphome-temp.git
#       ref: ble_write_action
#     components: [ ble_client ]

ble_client:
  - mac_address: C3:B3:F7:78:D8:53
    id: switchbot
    # maintain_connection: true
    # on_connect:
    #   then:
    #     - lambda: |-
    #         ESP_LOGD("ble_client_lambda", "Connected to BLE device");
    # on_disconnect:
    #   then:
    #     - lambda: |-
    #         ESP_LOGD("ble_client_lambda", "Disconnected from BLE device");  

switch:
  - platform: template
    name: "Switchbot Button"
    # optimistic: true

    turn_on_action:
      - ble_client.ble_write:
          id: switchbot
          service_uuid: CBA20D00-224D-11E6-9FB8-0002A5D5C51B
          characteristic_uuid: CBA20002-224D-11E6-9FB8-0002A5D5C51B
          value: [0x57, 0x01]
    id: switchbotswitch

  - platform: gpio
    name: "Relay"
    pin: GPIO14
    id: relay
    on_turn_on:
        - delay: 500ms
        - switch.turn_off: relay

binary_sensor:
  - platform: gpio
    pin: 
      number: GPIO12
      mode:
        input: true
        pullup: true
    name: "Button"
    id: hardwarebutton
    on_press:
      then:
        - switch.turn_on: switchbotswitch
        - switch.turn_on: relay

  - platform: gpio
    pin:
      number: GPIO27
      mode:
        input: true
        pullup: true
    name: "Board Button"
    id: boardbutton


  - platform: gpio
    name: "Sound"
    id: sound
    pin: 
      number: GPIO26
      mode:
        input: true
        pullup: true
    filters:
      - delayed_off: 1s
    on_press:
      then:
        - switch.turn_on: switchbotswitch
        - switch.turn_on: relay
        
sensor:
  - platform: adc
    pin: GPIO34
    name: "Sound level"
    update_interval: 0.5s
    filters:
      - multiply: 3.3 # see https://esphome.io/components/sensor/adc.html

# sensor:
#   - platform: pulse_counter
#     pin: GPIO12
#     unit_of_measurement: 'kWh'
#     name: 'Gas kW Meter'
    # filters:
    #   - multiply: 11.36266667 

    # total:
    #   unit_of_measurement: 'kWh'
    #   name: 'Energy Meter House'
      # filters:
      #   - multiply: 11.36266667 

  # - platform: pulse_counter
  #   pin: GPIO12
  #   name: 'Gas Pulse'
  #   update_interval: 5s

  #   total:
  #     name: 'Gas Pulse'

## E0:89:7E:84:0E:C2
# DC:23:4D:3F:87:15
## 8C:88:2B:60:00:21

  # - platform: xiaomi_hhccjcy01
  #   mac_address: DC:23:4D:E5:68:E8
  #   # mac_address: DC:23:4D:E5:6C:7B
  #   temperature:
  #     name: "Gary Plant Temperature"
  #   moisture:
  #     name: "Gary Plant Moisture"
  #   illuminance:
  #     name: "Gary Plant Illuminance"
  #   conductivity:
  #     name: "Gary Plant Soil Conductivity"
    # battery_level:
    #   name: "Gary Plant Battery Level"


  # - platform: adc
  #   pin: ADC15
  #   name: 'Gas Pulse'
  #   filters:
  #     - multiply: 3.3

# output:
#   - platform: gpio
#     pin: GPIO12
#     id: gpio_d1

  # - platform: ble_rssi
  #   mac_address: 00:24:e4:bf:ef:76
  #   name: "BLE RSSI value"

# ble_client:
#   - mac_address: 00:24:e4:bf:ef:76
#     id: ble_itag
#     on_connect:
#       then:
#         - lambda: |-
#             ESP_LOGD("ble_client_lambda", "Connected to BLE device");
#     on_disconnect:
#       then:
#         - lambda: |-
#             ESP_LOGD("ble_client_lambda", "Disconnected from BLE device");
