substitutions:
  name: boiler

<<: !include ./includes/common.yaml
<<: !include ./includes/bluetooth_proxy.yaml

logger:
  level: debug

sensor:
  - platform: bmp280_i2c
    i2c_id: bus_a
    temperature:
      name: "Temperature mono"
    address: 0x76
  - platform: bmp280_i2c
    i2c_id: bus_b
    temperature:
      name: "Temperature colour"
    address: 0x76

i2c:
  - id: bus_a
    sda: 21
    scl: 22
    scan: false
  - id: bus_b
    sda: 5
    scl: 18
    scan: false
