wifi:
  use_address: ${name}.iot.cns.me
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  reboot_timeout: 1800s
  
api:
  reboot_timeout: 0s
  encryption:
    key: !secret encryption_key

esphome:
  name: ${name}
  platform: ESP32
  board: esp32dev

ota:
  password: !secret device_password

logger:
  level: DEBUG
  baud_rate: 0

sensor:
  - platform: uptime
    name: Uptime
    update_interval: 60s

button:
  - platform: restart
    name: Restart

time:
  - platform: homeassistant
    id: homeassistant_time