substitutions:
  name: gascam

# <<: !include ./includes/common.yaml
# <<: !include ./includes/bluetooth_proxy.yaml


wifi:
  use_address: ${name}.iot.cns.me
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  reboot_timeout: 15min
  
api:
  reboot_timeout: 15min
  encryption:
    key: !secret encryption_key

esphome:
  name: ${name}

esp32:
  board: esp32dev
  # framework:
  #   type: esp-idf

ota:
  - platform: esphome
    password: !secret device_password

logger:
  level: DEBUG
  baud_rate: 0

sensor:
  - platform: uptime
    name: Uptime
    update_interval: 60s

button:
  - platform: restart
    name: Restart

time:
  - platform: homeassistant
    id: homeassistant_time

esp32_camera:
  name: Gas Cam
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32
  resolution: 1024x768
  # max_framerate: 1
  aec_mode: manual
  aec_value: 1200
  agc_mode: manual
  wb_mode: office


esp32_camera_web_server:
  - port: 8081
    mode: snapshot

output:
  # - platform: gpio
  #   pin: 4
  #   id: flash

  - platform: gpio
    pin: 12
    id: light_output

light:

  - platform: binary
    restore_mode: ALWAYS_OFF
    name: "Gascam Light"
    id: cam_flash
    output: light_output
    on_turn_on:
      - delay: 45s
      - light.turn_off: cam_flash

# web_server: