
esphome:
  name: halldoor

esp8266:
  board: esp8285

wifi:
  use_address: halldoor.iot.cns.me
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  reboot_timeout: 1800s


ota:
  password: !secret device_password

api:
  password: !secret device_password

logger:

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode:
        input: true
        pullup: true
      inverted: true
    name: "Sonoff Basic Button"
    on_press:
      - switch.toggle: relay

switch:
  - platform: gpio
    name: "Sonoff Basic Relay"
    pin: GPIO12
    id: relay
    restore_mode: ALWAYS_ON

status_led:
  pin:
    number: GPIO13
    inverted: yes

button:
  - platform: restart
    name: Restart