substitutions:
  name: printmonitor2

<<: !include ./includes/common.yaml
# <<: !include ./includes/bluetooth_proxy.yaml

esp32_camera:
  name: Print Cam
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32
  resolution: 1024x768

logger:
  level: DEBUG
  baud_rate: 0

esp32:
  board: esp32cam
  framework:
    type: esp-idf

# esp32_camera_web_server:
#   - port: 8081
#     mode: snapshot

output:
  - platform: gpio
    pin: 4
    id: flash

light:
  - platform: binary
    restore_mode: ALWAYS_OFF
    name: Print Cam Flash
    id: cam_flash
    output: flash
    on_turn_on:
      - delay: 45s
      - light.turn_off: cam_flash


switch:
  - platform: gpio
    pin: 
      number: GPIO12
    id: pms_set
    restore_mode: ALWAYS_ON
    name: "Start measuring"


sensor:
  - platform: pmsx003
    type: PMS5003ST
    uart_id: pmsx
    pm_1_0:
      name: "PM <1.0µm"
      filters:
        - debounce: 10s
    pm_2_5:
      name: "PM <2.5µm"
      filters:
        - debounce: 10s
    pm_10_0:
      name: "PM <10.0µm"
      filters:
        - debounce: 10s
    temperature:
      name: "Temperature"
      filters:
        - debounce: 10s
    humidity:
      name: "Humidity"
      filters:
        - debounce: 10s
    formaldehyde:
      name: "Formaldehyde"
      filters:
        - debounce: 10s
    update_interval: 30s

# web_server:

uart:
  - id: pmsx
    tx_pin: GPIO1
    rx_pin: GPIO3
    baud_rate: 9600