substitutions:
  name: test

<<: !include ./includes/common.yaml
# <<: !include ./includes/bluetooth_proxy.yaml

sensor:
  # - platform: vl53l0x
  #   name: "VL53L0x Distance"
  #   address: 0x29
  #   update_interval: 60s
  #   long_range: true
  #   timeout: 10000ms
    # enable_pin: GPO
  # - platform: pulse_counter
  #   id: water_flow_meter
  #   name: "Water Flow Rate"
  #   pin: GPIO15
  #   update_interval: 20s
  #   unit_of_measurement: L/min
  #   accuracy_decimals: 2
  #   filters: 
  #     - lambda: return (x / 27) * 60;
  # - platform: integration
  #   device_class: water
  #   name: "Water Consumption"
  #   sensor: water_flow_meter
  #   time_unit: min
  #   unit_of_measurement: L
  #   accuracy_decimals: 2
binary_sensor:
  - platform: gpio
    name: Hall Sensor 3144
    pin:
      number: GPIO13
      mode: INPUT_PULLUP
# i2c:
#   sda: GPIO15
#   frequency: 10kHz
#   scl: GPIO2
#   scan: true
#   id: bus_a

web_server:

logger:
  level: DEBUG
# esp32_ble_tracker:

# logger:
#   level: VERBOSE
#   baud_rate: 115200


# ble_client:
#   # Replace with the MAC address of your device.
#   - mac_address: F7:7C:63:56:1F:4E
#     id: itag_green

# binary_sensor:
#   - platform: template
#     id: green_button
#     name: "Green iTag Button"
#     filters:
#       delayed_off: 200ms

# sensor:
# # This entry registers and awaits notifications for the
# # characteristic that signals button presses. Each time
# # a notification is received, the corresponding binary_sensor
# # is briefly toggled.
#   - platform: ble_client
#     type: characteristic
#     ble_client_id: itag_green
#     name: "Green iTag btn"
#     service_uuid: 'ffe0'
#     characteristic_uuid: 'ffe1'
#     notify: true
#     update_interval: never
#     on_notify:
#       then:
#         - binary_sensor.template.publish:
#             id: green_button
#             state: ON
#         - binary_sensor.template.publish:
#             id: green_button
#             state: OFF
# # This entry queries the battery level. Some tags may not
# # support this characteristic, you will see 'Unknown' in the
# # HA frontend.
#   - platform: ble_client
#     type: characteristic
#     ble_client_id: itag_green
#     name: "Green iTag Battery"
#     service_uuid: '180f'
#     characteristic_uuid: '2a19'
#     icon: 'mdi:battery'
#     unit_of_measurement: '%'
# # This entry queries polls the RSSI when the tag is connected.
#   - platform: ble_client
#     type: rssi
#     ble_client_id: itag_green
#     name: "Green iTag RSSI"