name: "esphome"
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  compile:
    runs-on: ubuntu-latest
    name: esphome
    steps:
      - uses: docker://ghcr.io/esphome/esphome:2023.6.4
        with:
          args: compile *.yaml
