name: "esphome"
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  compile:
    name: esphome
    uses: docker://ghcr.io/esphome/esphome:latest
    with:
      args: compile *.yaml
